config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, controllers: { sessions: 'users/sessions' },
                     path: :gurus, 
                     path_names: { sign_in: :login, sign_out: :logout }
  
  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  get 'badges', to: 'user_badges#index'
  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  
  def self.rule
    %i[success_category success_on_first_try success_all_level]
  end

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image, :rule, :parameter, :description, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to [:admin, @badge], notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :image, :rule, :parameter, :description)
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.name %></td>
  <td class="align-middle">
    <%= image_tag(badge.image, size: 100) %>
  </td>
  <td class="align-middle"><%= badge.rule %></td>
  <td class="align-middle"><%= badge.parameter %></td>
  <td class="align-middle"><%= badge.description %></td>
  <td class="align-middle"><%= link_to t('.show_badge'), admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('.edit_badge'), edit_admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('.delete_badge'), admin_badge_path(badge),
                                       method: :delete,
                                       data: { confirm: t('.badge_del_confirm') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <div class="form-group">
    <p>
      <%= form.label :rule %>
      <%= form.select :rule, Badge.rule, prompt: true %>
    </p>

    <p>
      <%= form.label :image %>
      <%= form.text_field :image %>
    </p>

    <p>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :parameter %>
      <%= form.text_field :parameter %>
    </p>

    <p>
      <%= form.label :description %>
      <%= form.text_field :description %>
    </p>

    <p><%= form.submit class: "btn btn-primary" %></p>
<% end %>
</div>

app/views/admin/badges/edit.html.erb
<h1><%= t('.edit_title') %></h1>

<%= render 'form' %>
<%= link_to t('admin.answers.edit.back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4"><h4><%= t('.header') %></h4></div>

  <div class="col-12"><%= link_to t('.new_badge'), new_admin_badge_path %>
    <%= render 'shared/errors', resource: @badge %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= t('.name') %></th>
        <th><%= t('.image') %></th>
        <th><%= t('.rule') %></th>
        <th><%= t('.parameter') %></th>
        <th><%= t('.description') %></th>
        <th colspan="3"><%= t('tests.index.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <%= render @badges %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/badges/new.html.erb
<h1><%= t('.new_badge') %></h1>

<%= render 'form' %>
<%= link_to t('.back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong><%= t('.name') %></strong>
  <%= @badge.name %>
</p>

<p>
  <%= image_tag @badge.image, :alt => "image", size: 100 %>
</p>

<p>
  <strong><%= t('.rule') %></strong>
  <%= @badge.rule %>
</p>
<br>

<%= link_to t('.edit'), edit_admin_badge_path(@badge) %> |
<%= link_to t('.back'), admin_badges_path %>