config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, controllers: { sessions: 'users/sessions' },
                     path: :gurus, 
                     path_names: { sign_in: :login, sign_out: :logout }
  
  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  get 'badges', to: 'user_badges#index'
  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  PASSING_SCORE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, on: %i[create update]
  before_validation :add_result, on: :update

  scope :by_level, -> (level) { joins(:test).where(tests: { level: level }) }
  scope :passed, -> { where(passed: true) }

  def completed?
    current_question.nil?
  end

  def time_out?
    (test.timer - (Time.now - created_at)).to_i <= 0
  end

  def time_left
    self.test.timer - (Time.now - self.created_at).to_i if self.test.timer > 0
  end

  def test_question_qty
    test.questions.count
  end

  def percent_correct
    (correct_questions.to_f * 100 / test_question_qty).round(2)
  end

  def success?
    percent_correct >= PASSING_SCORE && !time_out?
  end

  def current_question_position
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def progress_percent
    (((current_question_position - 1).to_f / test_question_qty) * 100).round(1)
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  private
  
  def before_validation_set_question
    self.current_question = if new_record?
                              test.questions.first
                            else
                              test.questions.order(:id).where('id > ?', current_question.id).first
                            end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def add_result
    self.success? ? self.passed = true : self.passed = false
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed? || @test_passage.time_out?
      flash_options = { notice: t('.not_got_badge') }
      badges_count = current_user.badges.size
      current_user.badges << BadgeService.new(@test_passage).call
      flash_options = { notice: t('.got_badge') } if current_user.badges.size > badges_count
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage), flash_options
    else
      render :show
    end
  end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    result = service.call

    if service.success?
      current_user.gists.create!(question: @test_passage.current_question,
                                 gist_url: result.html_url)
      flash_options = { notice: t('.success', link: result.html_url) }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<% if @test_passage.success? %>
  <p>
    <span class="success"><%= t('.success', success_percent: @test_passage.percent_correct) %></span>
  </p>
<% else %>
  <p>
    <span class="fail"><%= t('.fail', fail_percent: @test_passage.percent_correct) %></span>
  </p>
<% end %>
<%= link_to t('.tests_list'), tests_path %>

app/views/test_passages/show.html.erb
<h2><%= t('.test_passing') %><%= @test_passage.test.title %> Test</h2>
<h2><%= t('.counter', current_question_position: @test_passage.current_question_position, questions_count: @test_passage.test.questions.count) %></h2>

<b>
  <%= @test_passage.current_question.body %>
</b>

<%= content_tag :div,
                "#{ t('.time_left') }",
                class: 'timer',
                data: { timer: @test_passage.time_left } %>

<div class="progress">
  <div class="progress-bar" id="progress-bar" data-progress="<%= @test_passage.progress_percent %>">
    <%= @test_passage.progress_percent %>
  </div>
</div>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ads_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to t('.gist_question'), gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('.next') %></p>
<% end %>