config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, controllers: { sessions: 'users/sessions' },
                     path: :gurus, 
                     path_names: { sign_in: :login, sign_out: :logout }
  
  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  get 'badges', to: 'user_badges#index'
  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
  validate :validate_answers_qty, on: :create
  scope :correct_answers, -> { where(correct: true) }

  private
  def validate_answers_qty
    errors.add(:question, :limit) if question.present? && question.answers.size >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  
  def self.rule
    %i[success_category success_on_first_try success_all_level]
  end

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image, :rule, :parameter, :description, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
  validates :title, presence: true
  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model

  attr_accessor :email, :message

  validates :email, presence: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :message, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord

  belongs_to :user
  belongs_to :question
  validates :gist_url, presence: true

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  validates :title, presence: true,
                    uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: -1 }
  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :by_category, -> (category_name) { joins(:category).where(category: {title: category_name}) }
  scope :visible_tests, -> { where(visible: true) }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  PASSING_SCORE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, on: %i[create update]
  before_validation :add_result, on: :update

  scope :by_level, -> (level) { joins(:test).where(tests: { level: level }) }
  scope :passed, -> { where(passed: true) }

  def completed?
    current_question.nil?
  end

  def time_out?
    (test.timer - (Time.now - created_at)).to_i <= 0
  end

  def time_left
    self.test.timer - (Time.now - self.created_at).to_i if self.test.timer > 0
  end

  def test_question_qty
    test.questions.count
  end

  def percent_correct
    (correct_questions.to_f * 100 / test_question_qty).round(2)
  end

  def success?
    percent_correct >= PASSING_SCORE && !time_out?
  end

  def current_question_position
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def progress_percent
    (((current_question_position - 1).to_f / test_question_qty) * 100).round(1)
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  private
  
  def before_validation_set_question
    self.current_question = if new_record?
                              test.questions.first
                            else
                              test.questions.order(:id).where('id > ?', current_question.id).first
                            end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def add_result
    self.success? ? self.passed = true : self.passed = false
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable
  
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
    
  def sort_user_tests_by_level(level)
    self.tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.type == 'Admin'
  end
  
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/models/users_test.rb
class UsersTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  
  before_action :set_test, only: %i[start]

  def index
    @tests = Test.visible_tests
  end

  def start
    if @test.questions.empty?
      redirect_to root_path, notice: t('.fail')
    else
      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test)
    end
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to 'TestGuru, dev by: Alexander Melekhin', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def flash_class(type)
    types = {
      "notice" => "alert alert-info", "success" => "alert alert-success",
      "error" => "alert alert-warning", "alert" => "alert alert-warning"
    }
    types[type]
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Редактирование вопроса: #{question.body}"
    else
      'Создание вопроса'
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => I18n.t('helpers.test.easy'), 
                  1 => I18n.t('helpers.test.elementary'), 
                  2 => I18n.t('helpers.test.advanced'), 
                  3 => I18n.t('helpers.test.hard')}.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end

  def test_header(test)
    if test.persisted?
      "Редактирование теста: #{test.title}"
    else
      'Создание теста'
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= t('.header') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= t('.header') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h4>
      <%= t('.header', count: resource.errors.count) %>:
    </h4>
    
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>" role="alert">
    <%= value.html_safe %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div align="center">
  <br>
  <%= current_year %>
  <br>
  <%= github_url('GodKIM91', 'TestGuru') %><br>
  <%= link_to t(".project"), 'https://thinknetica.com', target: '_blank' %>
  <p><%= link_to t('.feedback'), new_feedback_path %></p>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to t('.project'), root_path, class: 'navbar-brand' %>
  <% if current_user.present? && current_user.admin?  %>
    <%= link_to t('.tests_control'), admin_tests_path, class: 'navbar-brand' %>
    <%= link_to t('.badges_control'), admin_badges_path, class: 'navbar-brand' %>
    <%= link_to t('.gists'), admin_gists_path, class: 'navbar-brand' %>
  <% end %>

  <div class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome', user: current_user.first_name.empty? ? current_user.email : current_user.first_name) %>
      <%= link_to t('.badges'), badges_path, class: "btn btn-outline-primary btn-sm" %>
      <%= link_to t('.logout'), destroy_user_session_path, class: "btn btn-outline-primary btn-sm", method: :delete %>
    <% else %>
        <%= link_to t('.signup'), new_user_registration_path, class: "btn btn-outline-primary btn-sm" %>
        <%= link_to t('.login'), new_user_session_path, class: "btn btn-outline-primary btn-sm" %>
    <% end %>
  </span>
</nav>