config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, controllers: { sessions: 'users/sessions' },
                     path: :gurus, 
                     path_names: { sign_in: :login, sign_out: :logout }
  
  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  get 'badges', to: 'user_badges#index'
  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_question, only: %i[show destroy edit update]
  before_action :find_test, only: %i[index create new]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index
    questions = @test.questions.pluck(:body)
    render plain: questions.join("\n")
  end

  def show; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@test), notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test), notice: t('.success')
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  private 

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found!'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Редактирование вопроса: #{question.body}"
    else
      'Создание вопроса'
    end
  end
end

app/views/admin/questions/_form.erb
<h3><%= question_header(@question) %></h3>
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %>
    <%= form.text_field :body, value: @question.body %>
  </p><br>

  <p><%= form.submit %></p>
<% end %>
<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to link_to t('.show'), admin_question_path(question) %></td>
  <td><%= link_to link_to t('.edit'), edit_admin_question_path(question) %></td>
  <td><%= link_to link_to t('.delete'),
                  admin_question_path(question),
                  method: :delete,
                  data: {confirm: t('.del_confirm')} %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>

app/views/admin/questions/show.html.erb
<h2><%= t('.question_header', question: @question.body) %></h2>

<h3><%= t('.answers_list') %></h3>
<%= link_to t('.new_answer'), new_admin_question_answer_path(@question) %>
<ol>
  <%= render @question.answers %>
</ol>

<%= link_to t('.edit'), edit_admin_question_path(@question) %>
<%= link_to t('.delete'), admin_question_path(@question), method: :delete, data: { confirm: t('.del_confirm') } %>
<%= link_to t('.back'), admin_test_path(@question.test) %>